CREATE DATABASE IF NOT EXISTS trello CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE trello;
DROP TABLE IF EXISTS users_cards;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS lists;